name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Make Release on PyPI and Github
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Build a binary wheel
        run: |
          uv build

      - name: Check Distribution
        run: |
          uvx twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
