name: Run Demo
on: [push]


jobs:
  tests:
    name: Run Demo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        demo: ["getting_started", "beyond_galaxy", "component-showcase", "cross_correlation", "extension", "wdm"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: Install
        run:  uv sync --locked --group doctests

      - name: Install ipykernel
        run: uv run python -m ipykernel install --user --name halomod

      - name: Run Notebook
        run: |
          uv run papermill -k halomod docs/examples/${{ matrix.demo }}.ipynb output-${{ matrix.demo }}.ipynb

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: ${{ matrix.demo }}
          path: output-${{ matrix.demo }}.ipynb
